### ISSUE TITLE
Attempt to call method 'gsub' (a nil value) from project_config.lua:52

### ISSUE THREAD

**Issue by csy19960309** [Shatur/neovim-cmake#17] opened 2021-11-28 12:29 UTC
**Bug description**
Got the error message in the title.

**Steps to reproduce**

Nearly every operation raises that.

**Expected behavior**

**Screenshots**

**Environment**

- OS: WIndows 11
- Desktop environment: 
- Plugins commit hash: b5c756569ddc7548bc2e3d79786fbd5bb26c5993

**Additional context**

After taking back the _toString_ method, everything will be OK.

**Comment by Shatur** [comment] 2021-11-28 17:34
Can't reproduce. Could you provide your configuration?

**Comment by btaczala** [comment] 2021-12-01 19:38
@csy19960309 Had the same problem with config:
```
require("cmake").setup({
    parameters_file = "neovim.json",
    build_dir = Path:new('{cwd}', 'build', ''),
```
changing it to 
```
require("cmake").setup({
	parameters_file = "neovim.json",
	build_dir = tostring(Path:new("{cwd}", "build")),
```
fixed the issue.

**Comment by Shatur** [comment] 2021-12-01 19:40
Oh, you used `Plenary.Path` in your configuration.
Sorry, I didn't think this could be a breaking change, my bad.

**Comment by Shatur** [comment] 2021-12-01 19:42
Pinning and closing.

**Closed by Shatur** 2021-12-01 19:42 UTC
Labels: bug
